# Generated by Django 4.1 on 2022-08-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('user_pw', models.CharField(max_length=30)),
                ('user_email', models.EmailField(max_length=128)),
                ('user_name', models.CharField(max_length=10)),
                ('user_birth', models.IntegerField(max_length=6)),
                ('user_nickname', models.CharField(max_length=10)),
                ('user_university', models.CharField(max_length=15)),
                ('user_major', models.CharField(max_length=15)),
                ('user_interest', models.CharField(max_length=20)),
                ('user_register_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
